### PR TITLE
Bot Analytics

### PR DESCRIPTION
**Pull request by MTS11648**
This change will allow us to see how each bot is doing and what their versions are. If we are running multiple different versions at once, it will allow us to see which one performs better. If someone misconfigures the bot, the stats will show. I did this all during my audit hour, so there may or may not be a bug. Test before merging.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
I want to make an adjustment to this later that makes it include what Github version the code is running. That way, we can accurately point right to the exact commit the code runs.

**Comment by MTS11648** [comment]
@SpadesNeil I don't really keep up with all the different Github versions, but you could implement a variable into the code with it and modify the Slack message procedure to contain it.

**Comment by SpadesNeil** [comment]
capture

**Comment by MTS11648** [comment]
It should work properly now, apparently some genius at Microsoft thought it'd be funny to make WPF and regular Windows Forms work differently in regards to using the DateTime functions.

**Comment by MTS11648** [comment]
@SpadesNeil put some trust in me my dude

**Comment by SpadesNeil** [comment]
capture

mfw https://www.youtube.com/watch?v=r6ivUNKYf2o

**Pull request merged**
